module.exports = {
    survey: {
        output: {
            mode: 'tags-split',
            target: 'src/api/autoGenerated/survey.ts',
            schemas: 'src/api/autoGenerated/schemas',
            client: 'react-query',
            mock: false,
            clean: true,
            prettier: true,
            override: {
                mutator: {
                    path: 'src/api/apiClient.ts',
                    name: 'http',
                },
            },
        },
        input: {
            target: './swagger.json',
        },
    },
};
